kind: Service
apiVersion: v1
metadata:
  #Service name
  name: my-simple-app-service
spec:
  selector:
    app: simple-project-204912
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer